name: Prune stale images

on:
  schedule:
    - cron: '43 3 * * *'
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        sdk: [ java, kotlin, scala, columnar-java ]

    steps:
      - name: Prune old temporary images
        uses: vlaurin/action-ghcr-prune@0cf7d39f88546edd31965acba78cdcb0be14d641 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          organization: ${{ github.repository_owner }}
          user: ${{ github.repository_owner }}
          container: ${{ matrix.sdk }}-fit-performer
#          keep-younger-than: 7 # days
          # "changes" for Gerrit PR, "pull" for GitHub PR, and "sha" for arbitrary commit
          prune-tags-regexes: |
            ^(?:refs-)changes-
            ^(?:refs-)pull-
            ^(?:sha-)?[0-9a-f]{7,40}$

      - name: Prune untagged images
        uses: vlaurin/action-ghcr-prune@0cf7d39f88546edd31965acba78cdcb0be14d641 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #          organization: ${{ github.repository_owner }}
          user: ${{ github.repository_owner }}
          container: ${{ matrix.sdk }}-fit-performer
          prune-untagged: true
