name: Prune stale images

on:
  schedule:
    - cron: '43 3 * * *'
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run (uncheck to really delete)"
        type: boolean
        required: false
        default: true

jobs:
  prune:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    env:
      DRY_RUN: ${{ github.event.inputs.dry-run || 'true' }}

    strategy:
      matrix:
        sdk: [ java, kotlin, scala, columnar-java ]

    steps:
      - name: Prune old temporary images
        uses: vlaurin/action-ghcr-prune@0cf7d39f88546edd31965acba78cdcb0be14d641 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          organization: ${{ github.repository_owner }}
          user: ${{ github.repository_owner }}
          container: ${{ matrix.sdk }}-fit-performer
          dry-run: ${{ env.DRY_RUN }}
          keep-younger-than: 7 # days

          # "refs" because we only want to keep branches and tags, and we'll refer to those by simple name instead of full refs.
          # "changes" is for Gerrit users who omit the optional "refs/" prefix from "refs/changes/...".
          # "pull" is for GitHub.
          # "sha" is how `actions/docker-metadata-action` formats tags for type=sha
          # "pr" is how `actions/docker-metadata-action` formats tags for auto-detected GitHub PRs.
          # Lowercase hex, 7 to 40 characters -> assume it's a commit hash and therefore pruneable;
          #              woe unto those who name their branches "acceded", "defaced", or "effaced".
          prune-tags-regexes: |
            ^refs-
            ^changes-
            ^pull-
            ^pr-
            ^sha-
            ^[0-9a-f]{7,40}$

      - name: Prune untagged images
        uses: vlaurin/action-ghcr-prune@0cf7d39f88546edd31965acba78cdcb0be14d641 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #          organization: ${{ github.repository_owner }}
          user: ${{ github.repository_owner }}
          container: ${{ matrix.sdk }}-fit-performer
          dry-run: ${{ env.DRY_RUN }}
          prune-untagged: true
