name: Publish FIT performer on demand

run-name: "${{ inputs.sdk }} @ ${{ inputs.ref }}"

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "Full commit hash, or Gerrit patch set ref like: refs/changes/58/240858/6"
        required: true

      # Could use a matrix to build them all, but probably only care about one.
      sdk:
        type: choice
        description: SDK
        required: true
        options:
          - java
          - scala
          - kotlin
          - columnar-java
        default: java

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository_owner }}/${{ inputs.sdk }}-fit-performer
      IMAGE_TAG_PREFIX: tmp- # indicates the image may be pruned after some time
      GERRIT_BASE_URL: https://review.couchbase.org

    steps:
      - run: echo "SDK_REPO_SHORT_NAME=`basename ${{ github.repository }}`" >> $GITHUB_ENV
      - run: echo "GERRIT_REPO_URL=${{env.GERRIT_BASE_URL}}/${{env.SDK_REPO_SHORT_NAME}}" >> $GITHUB_ENV

      - name: Reconstruct Gerrit PR URL from last two components of ref (everything after third slash)
        run: echo "MAYBE_PR_LABEL=com.couchbase.pr=${{env.GERRIT_BASE_URL}}/c/${{env.SDK_REPO_SHORT_NAME}}/+/${REF#*/*/*/}" >> $GITHUB_ENV
        if: contains(inputs.ref, '/') # Don't set MAYBE_PR_LABEL if this doesn't look like a Gerrit PR
        env:
          REF: ${{ inputs.ref }}

      # This would be easier for native GitHub repos, which can use `actions/checkout` and specify the ref.
      - name: Check out Gerrit patch set
        run: |
          git clone --depth 1 --no-checkout ${{ env.GERRIT_REPO_URL }} .
          git fetch --depth 1 origin ${{ inputs.ref }}
          git checkout FETCH_HEAD
          git log --max-count=1
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Log in to the container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ env.IMAGE_TAG_PREFIX }}${{ inputs.ref }}
          flavor: latest=false
          # Override source and revision because the source came from an external repository.
          labels: |
            org.opencontainers.image.source=${{env.GERRIT_BASE_URL}}/admin/repos/${{env.SDK_REPO_SHORT_NAME}}
            org.opencontainers.image.revision=${{ env.COMMIT_HASH }}
            com.couchbase.github.actions.run=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ${{ env.MAYBE_PR_LABEL }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          build-args: SDK=${{ inputs.sdk }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Write job summary
        run: echo '```${{ steps.meta.outputs.tags }}```' >> $GITHUB_STEP_SUMMARY
