name: Sandbox

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  #  push:
  #    branches:
  #      - master
  #  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        include:
          - server: '7.6.5'
            java-distribution: 'temurin'
            java-version: '21'

          - server: 'community-7.6.2'
            java-distribution: 'temurin'
            java-version: '17'
            foo: 'beautiful'

    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sandbox
        run: |
          echo hello ${{ matrix.foo }} world
    
